version: '3.8'
services:
  dev-db:
    image: mysql:8.0.35
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: learningnestjs
      MYSQL_USER: gmususa
      MYSQL_PASSWORD: top-secret
    networks:
      - freecodecamp
  test-db:
    image: mysql:8.0.35
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: learningnestjs
      MYSQL_USER: gmususa
      MYSQL_PASSWORD: top-secret
    networks:
      - freecodecamp
networks:
  freecodecamp: